Remove unused variables
Avoid the following compilation errors when dumpBuf/dumpBn are not even
used, and when moving to add_library() with cmake.

        /usr/bin/ld: openair1/PHY/CODING/CMakeFiles/ldpc_cuda.dir/nrLDPC_decoder/nrLDPC_decoder_BG1_cuda.cu.o:/home/schmidtr/oai/openair1/PHY/CODING/nrLDPC_decoder/nrLDPC_CUDA_shared_param.h:71: multiple definition of `dumpBuf'; openair1/PHY/CODING/CMakeFiles/ldpc_cuda.dir/nrLDPC_decoder/nrLDPC_decoder_cuda.c.o:/home/schmidtr/oai/openair1/PHY/CODING/nrLDPC_decoder/nrLDPC_CUDA_shared_param.h:71: first defined here
       /usr/bin/ld: openair1/PHY/CODING/CMakeFiles/ldpc_cuda.dir/nrLDPC_decoder/nrLDPC_decoder_BG1_cuda.cu.o:/home/schmidtr/oai/openair1/PHY/CODING/nrLDPC_decoder/nrLDPC_CUDA_shared_param.h:72: multiple definition of `dumpBn'; openair1/PHY/CODING/CMakeFiles/ldpc_cuda.dir/nrLDPC_decoder/nrLDPC_decoder_cuda.c.o:/home/schmidtr/oai/openair1/PHY/CODING/nrLDPC_decoder/nrLDPC_CUDA_shared_param.h:72: first defined here